# Generated by Django 5.1.4 on 2025-07-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_response_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_newsletter_sent',
            field=models.BooleanField(default=False),
        ),
    ]
