# Generated by Django 5.1.4 on 2025-07-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_announcement_is_newsletter_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='is_newsletter_sent',
        ),
    ]
