# Generated by Django 5.1.4 on 2025-07-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_announcement_is_newsletter_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='announcements/images/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
