# Generated by Django 5.1.4 on 2025-07-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_announcement_images_announcement_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='video_url',
        ),
        migrations.AddField(
            model_name='announcement',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='announcements/videos/'),
        ),
    ]
