# Generated by Django 5.1.4 on 2025-07-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fam',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='otc',
            new_name='patronymic',
        ),
    ]
