# Generated by Django 5.1.4 on 2025-06-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en_us',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='headline_en_us',
            field=models.CharField(help_text='Введите название', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='headline_ru',
            field=models.CharField(help_text='Введите название', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='headline',
            field=models.CharField(help_text='Введите название', max_length=255),
        ),
    ]
